<?php
$items['1']=array('name'=>'Stone', 'shortname'=>'mmm');
$items['2']=array('name'=>'Grass', 'shortname'=>'mmm');
$items['3']=array('name'=>'Dirt', 'shortname'=>'mmm');
$items['4']=array('name'=>'Cobblestone', 'shortname'=>'mmm');
$items['5']=array('name'=>'Wooden Plank (Oak)', 'shortname'=>'mmm');
$items['5:1']=array('name'=>'Wooden Plank (Spruce)', 'shortname'=>'mmm');
$items['5:2']=array('name'=>'Wooden Plank (Birch)', 'shortname'=>'mmm');
$items['5:3']=array('name'=>'Wooden Plank (Jungle)', 'shortname'=>'mmm');
$items['6']=array('name'=>'Sapling (Oak)', 'shortname'=>'mmm');
$items['6:1']=array('name'=>'Sapling (Spruce)', 'shortname'=>'mmm');
$items['6:2']=array('name'=>'Sapling (Birch)', 'shortname'=>'mmm');
$items['6:3']=array('name'=>'Sapling (Jungle)', 'shortname'=>'mmm');
$items['7']=array('name'=>'Bedrock', 'shortname'=>'mmm');
$items['8']=array('name'=>'Water', 'shortname'=>'mmm');
$items['9']=array('name'=>'Water (No Spread)', 'shortname'=>'mmm');
$items['10']=array('name'=>'Lava', 'shortname'=>'mmm');
$items['11']=array('name'=>'Lava (No Spread)', 'shortname'=>'mmm');
$items['12']=array('name'=>'Sand', 'shortname'=>'mmm');
$items['13']=array('name'=>'Gravel', 'shortname'=>'mmm');
$items['14']=array('name'=>'Gold Ore', 'shortname'=>'mmm');
$items['15']=array('name'=>'Iron Ore', 'shortname'=>'mmm');
$items['16']=array('name'=>'Coal Ore', 'shortname'=>'mmm');
$items['17']=array('name'=>'Wood (Oak)', 'shortname'=>'mmm');
$items['17:1']=array('name'=>'Wood (Spruce)', 'shortname'=>'mmm');
$items['17:2']=array('name'=>'Wood (Birch)', 'shortname'=>'mmm');
$items['17:3']=array('name'=>'Wood (Jungle)', 'shortname'=>'mmm');
$items['18']=array('name'=>'Leaves (Oak)', 'shortname'=>'mmm');
$items['18:1']=array('name'=>'Leaves (Spruce)', 'shortname'=>'mmm');
$items['18:2']=array('name'=>'Leaves (Birch)', 'shortname'=>'mmm');
$items['18:3']=array('name'=>'Leaves (Jungle)', 'shortname'=>'mmm');
$items['19']=array('name'=>'Sponge', 'shortname'=>'mmm');
$items['20']=array('name'=>'Glass', 'shortname'=>'mmm');
$items['21']=array('name'=>'Lapis Lazuli Ore', 'shortname'=>'mmm');
$items['22']=array('name'=>'Lapis Lazuli Block', 'shortname'=>'mmm');
$items['23']=array('name'=>'Dispenser', 'shortname'=>'mmm');
$items['24']=array('name'=>'Sandstone', 'shortname'=>'mmm');
$items['24:1']=array('name'=>'Sandstone (Chiseled)', 'shortname'=>'mmm');
$items['24:2']=array('name'=>'Sandstone (Smooth)', 'shortname'=>'mmm');
$items['25']=array('name'=>'Note Block', 'shortname'=>'mmm');
$items['26']=array('name'=>'Bed (Block)', 'shortname'=>'mmm');
$items['27']=array('name'=>'Powered Rail', 'shortname'=>'mmm');
$items['28']=array('name'=>'Detector Rail', 'shortname'=>'mmm');
$items['29']=array('name'=>'Sticky Piston', 'shortname'=>'mmm');
$items['30']=array('name'=>'Web', 'shortname'=>'mmm');
$items['31']=array('name'=>'Tall Grass (Dead Shrub)', 'shortname'=>'mmm');
$items['31:1']=array('name'=>'Tall Grass', 'shortname'=>'mmm');
$items['31:2']=array('name'=>'Tall Grass (Fern)', 'shortname'=>'mmm');
$items['32']=array('name'=>'Dead Shrub', 'shortname'=>'mmm');
$items['33']=array('name'=>'Piston', 'shortname'=>'mmm');
$items['34']=array('name'=>'Piston (Head)', 'shortname'=>'mmm');
$items['35']=array('name'=>'Wool', 'shortname'=>'mmm');
$items['35:1']=array('name'=>'Orange Wool', 'shortname'=>'mmm');
$items['35:2']=array('name'=>'Magenta Wool', 'shortname'=>'mmm');
$items['35:3']=array('name'=>'Light Blue Wool', 'shortname'=>'mmm');
$items['35:4']=array('name'=>'Yellow Wool', 'shortname'=>'mmm');
$items['35:5']=array('name'=>'Lime Wool', 'shortname'=>'mmm');
$items['35:6']=array('name'=>'Pink Wool', 'shortname'=>'mmm');
$items['35:7']=array('name'=>'Gray Wool', 'shortname'=>'mmm');
$items['35:8']=array('name'=>'Light Gray Wool', 'shortname'=>'mmm');
$items['35:9']=array('name'=>'Cyan Wool', 'shortname'=>'mmm');
$items['35:10']=array('name'=>'Purple Wool', 'shortname'=>'mmm');
$items['35:11']=array('name'=>'Blue Wool', 'shortname'=>'mmm');
$items['35:12']=array('name'=>'Brown Wool', 'shortname'=>'mmm');
$items['35:13']=array('name'=>'Green Wool', 'shortname'=>'mmm');
$items['35:14']=array('name'=>'Red Wool', 'shortname'=>'mmm');
$items['35:15']=array('name'=>'Black Wool', 'shortname'=>'mmm');
$items['36']=array('name'=>'Piston (Moving)', 'shortname'=>'mmm');
$items['37']=array('name'=>'Dandelion', 'shortname'=>'mmm');
$items['38']=array('name'=>'Rose', 'shortname'=>'mmm');
$items['39']=array('name'=>'Brown Mushroom', 'shortname'=>'mmm');
$items['40']=array('name'=>'Red Mushroom', 'shortname'=>'mmm');
$items['41']=array('name'=>'Block of Gold', 'shortname'=>'mmm');
$items['42']=array('name'=>'Block of Iron', 'shortname'=>'mmm');
$items['43']=array('name'=>'Stone Slab (Double)', 'shortname'=>'mmm');
$items['43:1']=array('name'=>'Sandstone Slab (Double)', 'shortname'=>'mmm');
$items['43:2']=array('name'=>'Wooden Slab (Double)', 'shortname'=>'mmm');
$items['43:3']=array('name'=>'Cobblestone Slab (Double)', 'shortname'=>'mmm');
$items['43:4']=array('name'=>'Brick Slab (Double)', 'shortname'=>'mmm');
$items['43:5']=array('name'=>'Stone Brick Slab (Double)', 'shortname'=>'mmm');
$items['44']=array('name'=>'Stone Slab', 'shortname'=>'mmm');
$items['44:1']=array('name'=>'Sandstone Slab', 'shortname'=>'mmm');
$items['44:2']=array('name'=>'Wooden Slab', 'shortname'=>'mmm');
$items['44:3']=array('name'=>'Cobblestone Slab', 'shortname'=>'mmm');
$items['44:4']=array('name'=>'Brick Slab', 'shortname'=>'mmm');
$items['44:5']=array('name'=>'Stone Brick Slab', 'shortname'=>'mmm');
$items['45']=array('name'=>'Brick', 'shortname'=>'mmm');
$items['46']=array('name'=>'TNT', 'shortname'=>'mmm');
$items['47']=array('name'=>'Bookcase', 'shortname'=>'mmm');
$items['48']=array('name'=>'Moss Stone', 'shortname'=>'mmm');
$items['49']=array('name'=>'Obsidian', 'shortname'=>'mmm');
$items['50']=array('name'=>'Torch', 'shortname'=>'mmm');
$items['51']=array('name'=>'Fire', 'shortname'=>'mmm');
$items['52']=array('name'=>'Mob Spawner', 'shortname'=>'mmm');
$items['53']=array('name'=>'Wooden Stairs (Oak)', 'shortname'=>'mmm');
$items['54']=array('name'=>'Chest', 'shortname'=>'mmm');
$items['55']=array('name'=>'Redstone Wire', 'shortname'=>'mmm');
$items['56']=array('name'=>'Diamond Ore', 'shortname'=>'mmm');
$items['57']=array('name'=>'Block of Diamond', 'shortname'=>'mmm');
$items['58']=array('name'=>'Workbench', 'shortname'=>'mmm');
$items['59']=array('name'=>'Wheat (Crop)', 'shortname'=>'mmm');
$items['60']=array('name'=>'Farmland', 'shortname'=>'mmm');
$items['61']=array('name'=>'Furnace', 'shortname'=>'mmm');
$items['62']=array('name'=>'Furnace (Smelting)', 'shortname'=>'mmm');
$items['63']=array('name'=>'Sign (Block)', 'shortname'=>'mmm');
$items['64']=array('name'=>'Wood Door (Block)', 'shortname'=>'mmm');
$items['65']=array('name'=>'Ladder', 'shortname'=>'mmm');
$items['66']=array('name'=>'Rail', 'shortname'=>'mmm');
$items['67']=array('name'=>'Cobblestone Stairs', 'shortname'=>'mmm');
$items['68']=array('name'=>'Sign (Wall Block)', 'shortname'=>'mmm');
$items['69']=array('name'=>'Lever', 'shortname'=>'mmm');
$items['70']=array('name'=>'Stone Pressure Plate', 'shortname'=>'mmm');
$items['71']=array('name'=>'Iron Door (Block)', 'shortname'=>'mmm');
$items['72']=array('name'=>'Wooden Pressure Plate', 'shortname'=>'mmm');
$items['73']=array('name'=>'Redstone Ore', 'shortname'=>'mmm');
$items['74']=array('name'=>'Redstone Ore (Glowing)', 'shortname'=>'mmm');
$items['75']=array('name'=>'Redstone Torch (Off)', 'shortname'=>'mmm');
$items['76']=array('name'=>'Redstone Torch', 'shortname'=>'mmm');
$items['77']=array('name'=>'Button (Stone)', 'shortname'=>'mmm');
$items['78']=array('name'=>'Snow', 'shortname'=>'mmm');
$items['79']=array('name'=>'Ice', 'shortname'=>'mmm');
$items['80']=array('name'=>'Snow Block', 'shortname'=>'mmm');
$items['81']=array('name'=>'Cactus', 'shortname'=>'mmm');
$items['82']=array('name'=>'Clay Block', 'shortname'=>'mmm');
$items['83']=array('name'=>'Sugar Cane (Block)', 'shortname'=>'mmm');
$items['84']=array('name'=>'Jukebox', 'shortname'=>'mmm');
$items['85']=array('name'=>'Fence', 'shortname'=>'mmm');
$items['86']=array('name'=>'Pumpkin', 'shortname'=>'mmm');
$items['87']=array('name'=>'Netherrack', 'shortname'=>'mmm');
$items['88']=array('name'=>'Soul Sand', 'shortname'=>'mmm');
$items['89']=array('name'=>'Glowstone', 'shortname'=>'mmm');
$items['90']=array('name'=>'Portal', 'shortname'=>'mmm');
$items['91']=array('name'=>'Jack-O-Lantern', 'shortname'=>'mmm');
$items['92']=array('name'=>'Cake (Block)', 'shortname'=>'mmm');
$items['93']=array('name'=>'Redstone Repeater (Block Off)', 'shortname'=>'mmm');
$items['94']=array('name'=>'Redstone Repeater (Block On)', 'shortname'=>'mmm');
$items['95']=array('name'=>'Locked Chest', 'shortname'=>'mmm');
$items['96']=array('name'=>'Trapdoor', 'shortname'=>'mmm');
$items['97']=array('name'=>'Silverfish Stone', 'shortname'=>'mmm');
$items['97:1']=array('name'=>'Silverfish Cobblestone', 'shortname'=>'mmm');
$items['97:2']=array('name'=>'Silverfish Stone Brick', 'shortname'=>'mmm');
$items['98']=array('name'=>'Stone Bricks', 'shortname'=>'mmm');
$items['98:1']=array('name'=>'Mossy Stone Bricks', 'shortname'=>'mmm');
$items['98:2']=array('name'=>'Cracked Stone Bricks', 'shortname'=>'mmm');
$items['98:3']=array('name'=>'Chiseled Stone Brick', 'shortname'=>'mmm');
$items['99']=array('name'=>'Brown Mushroom (Block)', 'shortname'=>'mmm');
$items['100']=array('name'=>'Red Mushroom (Block)', 'shortname'=>'mmm');
$items['101']=array('name'=>'Iron Bars', 'shortname'=>'mmm');
$items['102']=array('name'=>'Glass Pane', 'shortname'=>'mmm');
$items['103']=array('name'=>'Melon (Block)', 'shortname'=>'mmm');
$items['104']=array('name'=>'Pumpkin Vine', 'shortname'=>'mmm');
$items['105']=array('name'=>'Melon Vine', 'shortname'=>'mmm');
$items['106']=array('name'=>'Vines', 'shortname'=>'mmm');
$items['107']=array('name'=>'Fence Gate', 'shortname'=>'mmm');
$items['108']=array('name'=>'Brick Stairs', 'shortname'=>'mmm');
$items['109']=array('name'=>'Stone Brick Stairs', 'shortname'=>'mmm');
$items['110']=array('name'=>'Mycelium', 'shortname'=>'mmm');
$items['111']=array('name'=>'Lily Pad', 'shortname'=>'mmm');
$items['112']=array('name'=>'Nether Brick', 'shortname'=>'mmm');
$items['113']=array('name'=>'Nether Brick Fence', 'shortname'=>'mmm');
$items['114']=array('name'=>'Nether Brick Stairs', 'shortname'=>'mmm');
$items['115']=array('name'=>'Nether Wart', 'shortname'=>'mmm');
$items['116']=array('name'=>'Enchantment Table', 'shortname'=>'mmm');
$items['117']=array('name'=>'Brewing Stand (Block)', 'shortname'=>'mmm');
$items['118']=array('name'=>'Cauldron (Block)', 'shortname'=>'mmm');
$items['119']=array('name'=>'End Portal', 'shortname'=>'mmm');
$items['120']=array('name'=>'End Portal Frame', 'shortname'=>'mmm');
$items['121']=array('name'=>'End Stone', 'shortname'=>'mmm');
$items['122']=array('name'=>'Dragon Egg', 'shortname'=>'mmm');
$items['123']=array('name'=>'Redstone Lamp', 'shortname'=>'mmm');
$items['124']=array('name'=>'Redstone Lamp (On)', 'shortname'=>'mmm');
$items['125']=array('name'=>'Oak-Wood Slab (Double)', 'shortname'=>'mmm');
$items['125:1']=array('name'=>'Spruce-Wood Slab (Double)', 'shortname'=>'mmm');
$items['125:2']=array('name'=>'Birch-Wood Slab (Double)', 'shortname'=>'mmm');
$items['125:3']=array('name'=>'Jungle-Wood Slab (Double)', 'shortname'=>'mmm');
$items['126']=array('name'=>'Oak-Wood Slab', 'shortname'=>'mmm');
$items['126:1']=array('name'=>'Spruce-Wood Slab', 'shortname'=>'mmm');
$items['126:2']=array('name'=>'Birch-Wood Slab', 'shortname'=>'mmm');
$items['126:3']=array('name'=>'Jungle-Wood Slab', 'shortname'=>'mmm');
$items['127']=array('name'=>'Coca Plant', 'shortname'=>'mmm');
$items['128']=array('name'=>'Sandstone Stairs', 'shortname'=>'mmm');
$items['129']=array('name'=>'Emerald Ore', 'shortname'=>'mmm');
$items['130']=array('name'=>'Ender Chest', 'shortname'=>'mmm');
$items['131']=array('name'=>'Tripwire Hook', 'shortname'=>'mmm');
$items['132']=array('name'=>'Tripwire', 'shortname'=>'mmm');
$items['133']=array('name'=>'Block of Emerald', 'shortname'=>'mmm');
$items['134']=array('name'=>'Wooden Stairs (Spruce)', 'shortname'=>'mmm');
$items['135']=array('name'=>'Wooden Stairs (Birch)', 'shortname'=>'mmm');
$items['136']=array('name'=>'Wooden Stairs (Jungle)', 'shortname'=>'mmm');
$items['137']=array('name'=>'Command Block', 'shortname'=>'mmm');
$items['138']=array('name'=>'Beacon', 'shortname'=>'mmm');
$items['139']=array('name'=>'Cobblestone Wall', 'shortname'=>'mmm');
$items['139:1']=array('name'=>'Mossy Cobblestone Wall', 'shortname'=>'mmm');
$items['140']=array('name'=>'Flower Pot (Block)', 'shortname'=>'mmm');
$items['141']=array('name'=>'Carrot (Crop)', 'shortname'=>'mmm');
$items['142']=array('name'=>'Potatoes (Crop)', 'shortname'=>'mmm');
$items['143']=array('name'=>'Button (Wood)', 'shortname'=>'mmm');
$items['144']=array('name'=>'Head Block (Skeleton)', 'shortname'=>'mmm');
$items['144:1']=array('name'=>'Head Block (Wither)', 'shortname'=>'mmm');
$items['144:2']=array('name'=>'Head Block (Zombie)', 'shortname'=>'mmm');
$items['144:3']=array('name'=>'Head Block (Steve)', 'shortname'=>'mmm');
$items['144:4']=array('name'=>'Head Block (Creeper)', 'shortname'=>'mmm');
$items['145']=array('name'=>'Anvil', 'shortname'=>'mmm');
$items['256']=array('name'=>'Iron Shovel', 'shortname'=>'mmm');
$items['257']=array('name'=>'Iron Pickaxe', 'shortname'=>'mmm');
$items['258']=array('name'=>'Iron Axe', 'shortname'=>'mmm');
$items['259']=array('name'=>'Flint and Steel', 'shortname'=>'mmm');
$items['260']=array('name'=>'Apple', 'shortname'=>'mmm');
$items['261']=array('name'=>'Bow', 'shortname'=>'mmm');
$items['262']=array('name'=>'Arrow', 'shortname'=>'mmm');
$items['263']=array('name'=>'Coal', 'shortname'=>'mmm');
$items['263:1']=array('name'=>'Charcoal', 'shortname'=>'mmm');
$items['264']=array('name'=>'Diamond Gem', 'shortname'=>'mmm');
$items['265']=array('name'=>'Iron Ingot', 'shortname'=>'mmm');
$items['266']=array('name'=>'Gold Ingot', 'shortname'=>'mmm');
$items['267']=array('name'=>'Iron Sword', 'shortname'=>'mmm');
$items['268']=array('name'=>'Wooden Sword', 'shortname'=>'mmm');
$items['269']=array('name'=>'Wooden Shovel', 'shortname'=>'mmm');
$items['270']=array('name'=>'Wooden Pickaxe', 'shortname'=>'mmm');
$items['271']=array('name'=>'Wooden Axe', 'shortname'=>'mmm');
$items['272']=array('name'=>'Stone Sword', 'shortname'=>'mmm');
$items['273']=array('name'=>'Stone Shovel', 'shortname'=>'mmm');
$items['274']=array('name'=>'Stone Pickaxe', 'shortname'=>'mmm');
$items['275']=array('name'=>'Stone Axe', 'shortname'=>'mmm');
$items['276']=array('name'=>'Diamond Sword', 'shortname'=>'mmm');
$items['277']=array('name'=>'Diamond Shovel', 'shortname'=>'mmm');
$items['278']=array('name'=>'Diamond Pickaxe', 'shortname'=>'mmm');
$items['279']=array('name'=>'Diamond Axe', 'shortname'=>'mmm');
$items['280']=array('name'=>'Stick', 'shortname'=>'mmm');
$items['281']=array('name'=>'Bowl', 'shortname'=>'mmm');
$items['282']=array('name'=>'Mushroom Stew', 'shortname'=>'mmm');
$items['283']=array('name'=>'Gold Sword', 'shortname'=>'mmm');
$items['284']=array('name'=>'Gold Shovel', 'shortname'=>'mmm');
$items['285']=array('name'=>'Gold Pickaxe', 'shortname'=>'mmm');
$items['286']=array('name'=>'Gold Axe', 'shortname'=>'mmm');
$items['287']=array('name'=>'String', 'shortname'=>'mmm');
$items['288']=array('name'=>'Feather', 'shortname'=>'mmm');
$items['289']=array('name'=>'Gunpowder', 'shortname'=>'mmm');
$items['290']=array('name'=>'Wooden Hoe', 'shortname'=>'mmm');
$items['291']=array('name'=>'Stone Hoe', 'shortname'=>'mmm');
$items['292']=array('name'=>'Iron Hoe', 'shortname'=>'mmm');
$items['293']=array('name'=>'Diamond Hoe', 'shortname'=>'mmm');
$items['294']=array('name'=>'Gold Hoe', 'shortname'=>'mmm');
$items['295']=array('name'=>'Wheat Seeds', 'shortname'=>'mmm');
$items['296']=array('name'=>'Wheat', 'shortname'=>'mmm');
$items['297']=array('name'=>'Bread', 'shortname'=>'mmm');
$items['298']=array('name'=>'Leather Helmet', 'shortname'=>'mmm');
$items['299']=array('name'=>'Leather Chestplate', 'shortname'=>'mmm');
$items['300']=array('name'=>'Leather Leggings', 'shortname'=>'mmm');
$items['301']=array('name'=>'Leather Boots', 'shortname'=>'mmm');
$items['302']=array('name'=>'Chainmail Helmet', 'shortname'=>'mmm');
$items['303']=array('name'=>'Chainmail Chestplate', 'shortname'=>'mmm');
$items['304']=array('name'=>'Chainmail Leggings', 'shortname'=>'mmm');
$items['305']=array('name'=>'Chainmail Boots', 'shortname'=>'mmm');
$items['306']=array('name'=>'Iron Helmet', 'shortname'=>'mmm');
$items['307']=array('name'=>'Iron Chestplate', 'shortname'=>'mmm');
$items['308']=array('name'=>'Iron Leggings', 'shortname'=>'mmm');
$items['309']=array('name'=>'Iron Boots', 'shortname'=>'mmm');
$items['310']=array('name'=>'Diamond Helmet', 'shortname'=>'mmm');
$items['311']=array('name'=>'Diamond Chestplate', 'shortname'=>'mmm');
$items['312']=array('name'=>'Diamond Leggings', 'shortname'=>'mmm');
$items['313']=array('name'=>'Diamond Boots', 'shortname'=>'mmm');
$items['314']=array('name'=>'Gold Helmet', 'shortname'=>'mmm');
$items['315']=array('name'=>'Gold Chestplate', 'shortname'=>'mmm');
$items['316']=array('name'=>'Gold Leggings', 'shortname'=>'mmm');
$items['317']=array('name'=>'Gold Boots', 'shortname'=>'mmm');
$items['318']=array('name'=>'Flint', 'shortname'=>'mmm');
$items['319']=array('name'=>'Raw Porkchop', 'shortname'=>'mmm');
$items['320']=array('name'=>'Cooked Porkchop', 'shortname'=>'mmm');
$items['321']=array('name'=>'Painting', 'shortname'=>'mmm');
$items['322']=array('name'=>'Gold Apple', 'shortname'=>'mmm');
$items['323']=array('name'=>'Sign', 'shortname'=>'mmm');
$items['324']=array('name'=>'Wooden Door', 'shortname'=>'mmm');
$items['325']=array('name'=>'Bucket', 'shortname'=>'mmm');
$items['326']=array('name'=>'Bucket (Water)', 'shortname'=>'mmm');
$items['327']=array('name'=>'Bucket (Lava)', 'shortname'=>'mmm');
$items['328']=array('name'=>'Minecart', 'shortname'=>'mmm');
$items['329']=array('name'=>'Saddle', 'shortname'=>'mmm');
$items['330']=array('name'=>'Iron Door', 'shortname'=>'mmm');
$items['331']=array('name'=>'Redstone Dust', 'shortname'=>'mmm');
$items['332']=array('name'=>'Snowball', 'shortname'=>'mmm');
$items['333']=array('name'=>'Boat', 'shortname'=>'mmm');
$items['334']=array('name'=>'Leather', 'shortname'=>'mmm');
$items['335']=array('name'=>'Bucket (Milk)', 'shortname'=>'mmm');
$items['336']=array('name'=>'Clay Brick', 'shortname'=>'mmm');
$items['337']=array('name'=>'Clay', 'shortname'=>'mmm');
$items['338']=array('name'=>'Sugar Cane', 'shortname'=>'mmm');
$items['339']=array('name'=>'Paper', 'shortname'=>'mmm');
$items['340']=array('name'=>'Book', 'shortname'=>'mmm');
$items['341']=array('name'=>'Slime Ball', 'shortname'=>'mmm');
$items['342']=array('name'=>'Storage Minecart', 'shortname'=>'mmm');
$items['343']=array('name'=>'Powered Minecart', 'shortname'=>'mmm');
$items['344']=array('name'=>'Egg', 'shortname'=>'mmm');
$items['345']=array('name'=>'Compass', 'shortname'=>'mmm');
$items['346']=array('name'=>'Fishing Rod', 'shortname'=>'mmm');
$items['347']=array('name'=>'Watch', 'shortname'=>'mmm');
$items['348']=array('name'=>'Glowstone Dust', 'shortname'=>'mmm');
$items['349']=array('name'=>'Raw Fish', 'shortname'=>'mmm');
$items['350']=array('name'=>'Cooked Fish', 'shortname'=>'mmm');
$items['351']=array('name'=>'Ink Sack', 'shortname'=>'mmm');
$items['351:1']=array('name'=>'Rose Red Dye', 'shortname'=>'mmm');
$items['351:2']=array('name'=>'Cactus Green Dye', 'shortname'=>'mmm');
$items['351:3']=array('name'=>'Coca Bean', 'shortname'=>'mmm');
$items['351:4']=array('name'=>'Lapis Lazuli', 'shortname'=>'mmm');
$items['351:5']=array('name'=>'Purple Dye', 'shortname'=>'mmm');
$items['351:6']=array('name'=>'Cyan Dye', 'shortname'=>'mmm');
$items['351:7']=array('name'=>'Light Gray Dye', 'shortname'=>'mmm');
$items['351:8']=array('name'=>'Gray Dye', 'shortname'=>'mmm');
$items['351:9']=array('name'=>'Pink Dye', 'shortname'=>'mmm');
$items['351:10']=array('name'=>'Lime Dye', 'shortname'=>'mmm');
$items['351:11']=array('name'=>'Dandelion Yellow Dye', 'shortname'=>'mmm');
$items['351:12']=array('name'=>'Light Blue Dye', 'shortname'=>'mmm');
$items['351:13']=array('name'=>'Magenta Dye', 'shortname'=>'mmm');
$items['351:14']=array('name'=>'Orange Dye', 'shortname'=>'mmm');
$items['351:15']=array('name'=>'Bone Meal', 'shortname'=>'mmm');
$items['352']=array('name'=>'Bone', 'shortname'=>'mmm');
$items['353']=array('name'=>'Sugar', 'shortname'=>'mmm');
$items['354']=array('name'=>'Cake', 'shortname'=>'mmm');
$items['355']=array('name'=>'Bed', 'shortname'=>'mmm');
$items['356']=array('name'=>'Redstone Repeater', 'shortname'=>'mmm');
$items['357']=array('name'=>'Cookie', 'shortname'=>'mmm');
$items['358']=array('name'=>'Map', 'shortname'=>'mmm');
$items['359']=array('name'=>'Shears', 'shortname'=>'mmm');
$items['360']=array('name'=>'Melon (Slice)', 'shortname'=>'mmm');
$items['361']=array('name'=>'Pumpkin Seeds', 'shortname'=>'mmm');
$items['362']=array('name'=>'Melon Seeds', 'shortname'=>'mmm');
$items['363']=array('name'=>'Raw Beef', 'shortname'=>'mmm');
$items['364']=array('name'=>'Steak', 'shortname'=>'mmm');
$items['365']=array('name'=>'Raw Chicken', 'shortname'=>'mmm');
$items['366']=array('name'=>'Cooked Chicken', 'shortname'=>'mmm');
$items['367']=array('name'=>'Rotten Flesh', 'shortname'=>'mmm');
$items['368']=array('name'=>'Ender Pearl', 'shortname'=>'mmm');
$items['369']=array('name'=>'Blaze Rod', 'shortname'=>'mmm');
$items['370']=array('name'=>'Ghast Tear', 'shortname'=>'mmm');
$items['371']=array('name'=>'Gold Nugget', 'shortname'=>'mmm');
$items['372']=array('name'=>'Nether Wart Seeds', 'shortname'=>'mmm');
$items['373']=array('name'=>'Water Bottle', 'shortname'=>'mmm');
$items['373:16']=array('name'=>'Awkward Potion', 'shortname'=>'mmm');
$items['373:32']=array('name'=>'Thick Potion', 'shortname'=>'mmm');
$items['373:64']=array('name'=>'Mundane Potion', 'shortname'=>'mmm');
$items['373:8193']=array('name'=>'Regeneration Potion (0:45)', 'shortname'=>'mmm');
$items['373:8194']=array('name'=>'Swiftness Potion (3:00)', 'shortname'=>'mmm');
$items['373:8195']=array('name'=>'Fire Resistance Potion (3:00)', 'shortname'=>'mmm');
$items['373:8196']=array('name'=>'Poison Potion (0:45)', 'shortname'=>'mmm');
$items['373:8197']=array('name'=>'Healing Potion', 'shortname'=>'mmm');
$items['373:8198']=array('name'=>'Night Vision Potion (3:00)', 'shortname'=>'mmm');
$items['373:8200']=array('name'=>'Weakness Potion (1:30)', 'shortname'=>'mmm');
$items['373:8201']=array('name'=>'Strength Potion (3:00)', 'shortname'=>'mmm');
$items['373:8202']=array('name'=>'Slowness Potion (1:30)', 'shortname'=>'mmm');
$items['373:8204']=array('name'=>'Harming Potion', 'shortname'=>'mmm');
$items['373:8206']=array('name'=>'Invisibility Potion (3:00)', 'shortname'=>'mmm');
$items['373:8225']=array('name'=>'Regeneration Potion II (0:22)', 'shortname'=>'mmm');
$items['373:8226']=array('name'=>'Swiftness Potion II (1:30)', 'shortname'=>'mmm');
$items['373:8228']=array('name'=>'Poison Potion II (0:22)', 'shortname'=>'mmm');
$items['373:8229']=array('name'=>'Healing Potion II', 'shortname'=>'mmm');
$items['373:8233']=array('name'=>'Strength Potion II (1:30)', 'shortname'=>'mmm');
$items['373:8236']=array('name'=>'Harming Potion II', 'shortname'=>'mmm');
$items['373:8257']=array('name'=>'Regeneration Potion (2:00)', 'shortname'=>'mmm');
$items['373:8258']=array('name'=>'Swiftness Potion (8:00)', 'shortname'=>'mmm');
$items['373:8259']=array('name'=>'Fire Resistance Potion (8:00)', 'shortname'=>'mmm');
$items['373:8260']=array('name'=>'Poison Potion (2:00)', 'shortname'=>'mmm');
$items['373:8262']=array('name'=>'Night Vision Potion (8:00)', 'shortname'=>'mmm');
$items['373:8264']=array('name'=>'Weakness Potion (4:00)', 'shortname'=>'mmm');
$items['373:8265']=array('name'=>'Strength Potion (8:00)', 'shortname'=>'mmm');
$items['373:8266']=array('name'=>'Slowness Potion (4:00)', 'shortname'=>'mmm');
$items['373:8270']=array('name'=>'Invisibility Potion (8:00)', 'shortname'=>'mmm');
$items['373:16385']=array('name'=>'Regeneration Splash (0:33)', 'shortname'=>'mmm');
$items['373:16386']=array('name'=>'Swiftness Splash (2:15)', 'shortname'=>'mmm');
$items['373:16387']=array('name'=>'Fire Resistance Splash (2:15)', 'shortname'=>'mmm');
$items['373:16388']=array('name'=>'Poison Splash (0:33)', 'shortname'=>'mmm');
$items['373:16389']=array('name'=>'Healing Splash', 'shortname'=>'mmm');
$items['373:16390']=array('name'=>'Night Vision Splash (2:15)', 'shortname'=>'mmm');
$items['373:16392']=array('name'=>'Weakness Splash (1:07)', 'shortname'=>'mmm');
$items['373:16393']=array('name'=>'Strength Splash (2:15)', 'shortname'=>'mmm');
$items['373:16394']=array('name'=>'Slowness Splash (1:07)', 'shortname'=>'mmm');
$items['373:16396']=array('name'=>'Harming Splash', 'shortname'=>'mmm');
$items['373:16398']=array('name'=>'Invisibility Splash (2:15)', 'shortname'=>'mmm');
$items['373:16417']=array('name'=>'Regeneration Splash II (0:16)', 'shortname'=>'mmm');
$items['373:16418']=array('name'=>'Swiftness Splash II (1:07)', 'shortname'=>'mmm');
$items['373:16420']=array('name'=>'Poison Splash II (0:16)', 'shortname'=>'mmm');
$items['373:16421']=array('name'=>'Healing Splash II', 'shortname'=>'mmm');
$items['373:16425']=array('name'=>'Strength Splash II (1:07)', 'shortname'=>'mmm');
$items['373:16428']=array('name'=>'Harming Splash II', 'shortname'=>'mmm');
$items['373:16449']=array('name'=>'Regeneration Splash (1:30)', 'shortname'=>'mmm');
$items['373:16450']=array('name'=>'Swiftness Splash (6:00)', 'shortname'=>'mmm');
$items['373:16451']=array('name'=>'Fire Resistance Splash (6:00)', 'shortname'=>'mmm');
$items['373:16452']=array('name'=>'Poison Splash (1:30)', 'shortname'=>'mmm');
$items['373:16454']=array('name'=>'Night Vision Splash (6:00)', 'shortname'=>'mmm');
$items['373:16456']=array('name'=>'Weakness Splash (3:00)', 'shortname'=>'mmm');
$items['373:16457']=array('name'=>'Strength Splash (6:00)', 'shortname'=>'mmm');
$items['373:16458']=array('name'=>'Slowness Splash (3:00)', 'shortname'=>'mmm');
$items['373:16462']=array('name'=>'Invisibility Splash (6:00)', 'shortname'=>'mmm');
$items['374']=array('name'=>'Glass Bottle', 'shortname'=>'mmm');
$items['375']=array('name'=>'Spider Eye', 'shortname'=>'mmm');
$items['376']=array('name'=>'Fermented Spider Eye', 'shortname'=>'mmm');
$items['377']=array('name'=>'Blaze Powder', 'shortname'=>'mmm');
$items['378']=array('name'=>'Magma Cream', 'shortname'=>'mmm');
$items['379']=array('name'=>'Brewing Stand', 'shortname'=>'mmm');
$items['380']=array('name'=>'Cauldron', 'shortname'=>'mmm');
$items['381']=array('name'=>'Eye of Ender', 'shortname'=>'mmm');
$items['382']=array('name'=>'Glistering Melon (Slice)', 'shortname'=>'mmm');
$items['383:50']=array('name'=>'Spawn Egg (Creeper)', 'shortname'=>'mmm');
$items['383:51']=array('name'=>'Spawn Egg (Skeleton)', 'shortname'=>'mmm');
$items['383:52']=array('name'=>'Spawn Egg (Spider)', 'shortname'=>'mmm');
$items['383:54']=array('name'=>'Spawn Egg (Zombie)', 'shortname'=>'mmm');
$items['383:55']=array('name'=>'Spawn Egg (Slime)', 'shortname'=>'mmm');
$items['383:56']=array('name'=>'Spawn Egg (Ghast)', 'shortname'=>'mmm');
$items['383:57']=array('name'=>'Spawn Egg (Zombie Pigmen)', 'shortname'=>'mmm');
$items['383:58']=array('name'=>'Spawn Egg (Endermen)', 'shortname'=>'mmm');
$items['383:59']=array('name'=>'Spawn Egg (Cave Spider)', 'shortname'=>'mmm');
$items['383:60']=array('name'=>'Spawn Egg (Silverfish)', 'shortname'=>'mmm');
$items['383:61']=array('name'=>'Spawn Egg (Blaze)', 'shortname'=>'mmm');
$items['383:62']=array('name'=>'Spawn Egg (Magma Cube)', 'shortname'=>'mmm');
$items['383:65']=array('name'=>'Spawn Egg (Bat)', 'shortname'=>'mmm');
$items['383:66']=array('name'=>'Spawn Egg (Witch)', 'shortname'=>'mmm');
$items['383:90']=array('name'=>'Spawn Egg (Pig)', 'shortname'=>'mmm');
$items['383:91']=array('name'=>'Spawn Egg (Sheep)', 'shortname'=>'mmm');
$items['383:92']=array('name'=>'Spawn Egg (Cow)', 'shortname'=>'mmm');
$items['383:93']=array('name'=>'Spawn Egg (Chicken)', 'shortname'=>'mmm');
$items['383:94']=array('name'=>'Spawn Egg (Squid)', 'shortname'=>'mmm');
$items['383:95']=array('name'=>'Spawn Egg (Wolf)', 'shortname'=>'mmm');
$items['383:96']=array('name'=>'Spawn Egg (Mooshroom)', 'shortname'=>'mmm');
$items['383:98']=array('name'=>'Spawn Egg (Ocelot)', 'shortname'=>'mmm');
$items['383:120']=array('name'=>'Spawn Egg (Villager)', 'shortname'=>'mmm');
$items['384']=array('name'=>'Bottle of Enchanting', 'shortname'=>'mmm');
$items['385']=array('name'=>'Fire Charge', 'shortname'=>'mmm');
$items['386']=array('name'=>'Book and Quill', 'shortname'=>'mmm');
$items['387']=array('name'=>'Written Book', 'shortname'=>'mmm');
$items['388']=array('name'=>'Emerald', 'shortname'=>'mmm');
$items['389']=array('name'=>'Item Frame', 'shortname'=>'mmm');
$items['390']=array('name'=>'Flower Pot', 'shortname'=>'mmm');
$items['391']=array('name'=>'Carrot', 'shortname'=>'mmm');
$items['392']=array('name'=>'Potato', 'shortname'=>'mmm');
$items['393']=array('name'=>'Baked Potato', 'shortname'=>'mmm');
$items['394']=array('name'=>'Poisonous Potato', 'shortname'=>'mmm');
$items['395']=array('name'=>'Empty Map', 'shortname'=>'mmm');
$items['396']=array('name'=>'Golden Carrot', 'shortname'=>'mmm');
$items['397']=array('name'=>'Head (Skeleton)', 'shortname'=>'mmm');
$items['397:1']=array('name'=>'Head (Wither)', 'shortname'=>'mmm');
$items['397:2']=array('name'=>'Head (Zombie)', 'shortname'=>'mmm');
$items['397:3']=array('name'=>'Head (Steve)', 'shortname'=>'mmm');
$items['397:4']=array('name'=>'Head (Creeper)', 'shortname'=>'mmm');
$items['398']=array('name'=>'Carrot on a Stick', 'shortname'=>'mmm');
$items['399']=array('name'=>'Nether Star', 'shortname'=>'mmm');
$items['400']=array('name'=>'Pumpkin Pie', 'shortname'=>'mmm');
$items['2256']=array('name'=>'Music Disk (13)', 'shortname'=>'mmm');
$items['2257']=array('name'=>'Music Disk (Cat)', 'shortname'=>'mmm');
$items['2258']=array('name'=>'Music Disk (Blocks)', 'shortname'=>'mmm');
$items['2259']=array('name'=>'Music Disk (Chirp)', 'shortname'=>'mmm');
$items['2260']=array('name'=>'Music Disk (Far)', 'shortname'=>'mmm');
$items['2261']=array('name'=>'Music Disk (Mall)', 'shortname'=>'mmm');
$items['2262']=array('name'=>'Music Disk (Mellohi)', 'shortname'=>'mmm');
$items['2263']=array('name'=>'Music Disk (Stal)', 'shortname'=>'mmm');
$items['2264']=array('name'=>'Music Disk (Strad)', 'shortname'=>'mmm');
$items['2265']=array('name'=>'Music Disk (Ward)', 'shortname'=>'mmm');
$items['2266']=array('name'=>'Music Disk (11)', 'shortname'=>'mmm');
  

function get_item_name($id, $dur) {
  global $items;
  $id = strval($id);
  $itemcode = $id;
  if ($dur != 0) {
    $itemcode .= ':' . $dur;
  }

  if (array_key_exists($itemcode, $items)) {
    $name = $items[$itemcode]['name'];
  } else if (array_key_exists($id, $items)) {
    $name = $items[$id]['name'] . " (damaged)";
  } else {
    $name = $itemcode;
  }


  return $name;
}


function get_item_shortname($id, $dur) {
  global $items;
  $id = strval($id);
  $itemcode = $id;
  if ($dur != 0) {
    $itemcode .= ':' . $dur;
  }

  if (array_key_exists($itemcode, $items)) {
    $name = $items[$itemcode]['shortname'];
  } else {
    $name = $itemcode;
  }


  return $name;
}


